version: '3'

services:
  composer:
    image: graze/composer
    volumes:
      - .:/usr/src/app
      - ~/.composer:/home/composer/.composer

  php-55:
    image: graze/php-alpine:5-test
    volumes:
      - .:/srv
    working_dir: /srv
